/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CinnamonTypeController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CinnamonType;

/**
 *
 * @author sajja
 */
public class CinnamanTypeForm extends javax.swing.JInternalFrame {

    static DefaultTableModel dtmCT;
//
//    private String passdate;

    /**
     * Creates new form AdminUpdateStoreForm
     */
    public CinnamanTypeForm() {
        initComponents();

        dtmCT = (DefaultTableModel) cinnamonTypeListTable.getModel();
//
//        //get date from main form
//        passdate = MainForm.passDate();
        //set Store table
        setStoreList();
//
//        d_FTextField.setText(passdate);
//        d_TTextField.setText(passdate);

    }

    private static void setStoreList() {
        dtmCT.setRowCount(0);

        try {
            ArrayList<CinnamonType> allCinnamon = CinnamonTypeController.getAllCinnamon();
            for (CinnamonType cinnamonType : allCinnamon) {
                String ar[] = {cinnamonType.getCid(), cinnamonType.getType(), String.valueOf(cinnamonType.getPrice())};
                dtmCT.addRow(ar);

            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CinnamanTypeForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        New = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        cidNTextField = new javax.swing.JTextField();
        typeNTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        priceNTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        priceUTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cidUTextField = new javax.swing.JTextField();
        typeUTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        upDateButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cidRTextField = new javax.swing.JTextField();
        typeRTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        priceRTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cinnamonTypeListTable = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        New.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel19.setText("CID:");

        cidNTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidNTextFieldActionPerformed(evt);
            }
        });

        typeNTextField.setEditable(false);
        typeNTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeNTextFieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel20.setText("Type");

        priceNTextField.setEditable(false);
        priceNTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceNTextFieldActionPerformed(evt);
            }
        });
        priceNTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priceNTextFieldKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel5.setText("Price Per 1 Kg");

        addButton.setBackground(new java.awt.Color(51, 102, 255));
        addButton.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        addButton.setText("Add");
        addButton.setEnabled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        addButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 235, Short.MAX_VALUE)
                        .addComponent(addButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(priceNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typeNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cidNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cidNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(typeNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(priceNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(addButton)
                .addContainerGap())
        );

        New.addTab("New", jPanel2);

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel13.setText("Price Per 1 Kg");

        priceUTextField.setEditable(false);
        priceUTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceUTextFieldActionPerformed(evt);
            }
        });
        priceUTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priceUTextFieldKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel15.setText("CID");

        cidUTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidUTextFieldActionPerformed(evt);
            }
        });

        typeUTextField.setEditable(false);
        typeUTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeUTextFieldActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel16.setText("Type :");

        upDateButton.setBackground(new java.awt.Color(51, 102, 255));
        upDateButton.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        upDateButton.setText("UpDate");
        upDateButton.setEnabled(false);
        upDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upDateButtonActionPerformed(evt);
            }
        });
        upDateButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                upDateButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typeUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cidUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(upDateButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cidUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(typeUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(priceUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(upDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        New.addTab("UpDate", jPanel1);

        jLabel17.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel17.setText("CID");

        cidRTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidRTextFieldActionPerformed(evt);
            }
        });

        typeRTextField.setEditable(false);
        typeRTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeRTextFieldActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel18.setText("Type :");

        priceRTextField.setEditable(false);
        priceRTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceRTextFieldActionPerformed(evt);
            }
        });
        priceRTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priceRTextFieldKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel4.setText("Price Per 1 Kg");

        removeButton.setBackground(new java.awt.Color(51, 102, 255));
        removeButton.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        removeButton.setText("Remove");
        removeButton.setEnabled(false);
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        removeButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                removeButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typeRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cidRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(priceRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(103, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(removeButton)
                        .addGap(10, 10, 10))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cidRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(typeRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(priceRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(removeButton)
                .addContainerGap())
        );

        New.addTab("Remove", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(New, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(New, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cinnamonTypeListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CID", "Type", "Price Per 1 Kg"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cinnamonTypeListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cinnamonTypeListTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(cinnamonTypeListTable);

        jLabel25.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 102, 255));
        jLabel25.setText("Cinnamon Type List");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel27.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel27.setText("Cinnamon Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceUTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceUTextFieldActionPerformed

        upDateButton.requestFocus();
    }//GEN-LAST:event_priceUTextFieldActionPerformed

    private void priceUTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceUTextFieldKeyReleased
//        CheckNumber.checkDecimal(quntityUTextField);
    }//GEN-LAST:event_priceUTextFieldKeyReleased

    private void cidUTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidUTextFieldActionPerformed
        String cid = cidUTextField.getText();
        if (!"".equals(cid)) {

            try {
                CinnamonType cinnamonType = CinnamonTypeController.getCinnamonFromCID(cid);
                if (cinnamonType != null) {
                    typeUTextField.setEditable(true);
                    priceUTextField.setEditable(true);

                    typeUTextField.setText(cinnamonType.getType());
                    priceUTextField.setText(String.valueOf(cinnamonType.getPrice()));
                    
                    upDateButton.setEnabled(true);

                    typeUTextField.requestFocus();

                } else {
                    JOptionPane.showMessageDialog(cidUTextField, "This Cinnamaon ID not Valid.");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(cidUTextField, "Enter Cinnamon ID.");
        }

    }//GEN-LAST:event_cidUTextFieldActionPerformed

    private void typeUTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeUTextFieldActionPerformed
        priceUTextField.requestFocus();
    }//GEN-LAST:event_typeUTextFieldActionPerformed

    private void cidRTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidRTextFieldActionPerformed
        String cid = cidRTextField.getText();
        if (!"".equals(cid)) {

            try {
                CinnamonType cinnamonType = CinnamonTypeController.getCinnamonFromCID(cid);
                if (cinnamonType != null) {

                    typeRTextField.setText(cinnamonType.getType());
                    priceRTextField.setText(String.valueOf(cinnamonType.getPrice()));
                    removeButton.setEnabled(true);

                    typeRTextField.requestFocus();

                } else {
                    JOptionPane.showMessageDialog(cidRTextField, "This Cinnamaon ID not Valid.");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(cidRTextField, "Enter Cinnamon ID.");
        }
    }//GEN-LAST:event_cidRTextFieldActionPerformed

    private void typeRTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeRTextFieldActionPerformed
 
    }//GEN-LAST:event_typeRTextFieldActionPerformed

    private void priceRTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceRTextFieldActionPerformed

    }//GEN-LAST:event_priceRTextFieldActionPerformed

    private void priceRTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceRTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_priceRTextFieldKeyReleased

    private void cidNTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidNTextFieldActionPerformed
        String cid = cidNTextField.getText();
        if (!"".equals(cid)) {

            try {
                CinnamonType cinnamonType = CinnamonTypeController.getCinnamonFromCID(cid);
                if (cinnamonType == null) {
                    cidNTextField.setEditable(true);
                    typeNTextField.setEditable(true);
                    priceNTextField.setEditable(true);

                    typeNTextField.requestFocus();

                } else {
                    JOptionPane.showMessageDialog(cidNTextField, "This Cinnamaon ID already Added.");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(cidNTextField, "Enter Cinnamon ID.");
        }


    }//GEN-LAST:event_cidNTextFieldActionPerformed

    private void typeNTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeNTextFieldActionPerformed
        priceNTextField.requestFocus();
    }//GEN-LAST:event_typeNTextFieldActionPerformed

    private void priceNTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceNTextFieldActionPerformed
        String price = priceNTextField.getText();
        if (!"".equals(price)) {
            addButton.setEnabled(true);
            addButton.requestFocus();
        } else {
            JOptionPane.showMessageDialog(priceNTextField, "Enter Price per 1 Kg");
        }

    }//GEN-LAST:event_priceNTextFieldActionPerformed

    private void priceNTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceNTextFieldKeyReleased
//        CheckNumber.checkDecimal(quntityNTextField);
    }//GEN-LAST:event_priceNTextFieldKeyReleased

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String cid = cidNTextField.getText();
        String type = typeNTextField.getText();
        String price = priceNTextField.getText();

        if (!"".equals(cid) & !"".equals(type) & !"".equals(price)) {
            CinnamonType cinnamonType = new CinnamonType(cid, type, Double.parseDouble(price));
            try {
                int addType = CinnamonTypeController.addType(cinnamonType);
                if (addType > 0) {

                    //refresh store list
                    setStoreList();

                    typeNTextField.setEditable(false);
                    priceNTextField.setEditable(false);

                    addButton.setEnabled(false);

                    cidNTextField.setText("");
                    typeNTextField.setText("");
                    priceNTextField.setText("");

                    JOptionPane.showMessageDialog(addButton, "New Cinnamon Type entered.");
                } else {
                    JOptionPane.showMessageDialog(addButton, "Try Again.");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(CinnamanTypeForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(addButton, "Enter the all Data.");
        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void upDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upDateButtonActionPerformed
        String cid = cidUTextField.getText();
        String type = typeUTextField.getText();
        String price = priceUTextField.getText();

        if (!"".equals(cid) & !"".equals(type) & !"".equals(price)) {
            CinnamonType cinnamonType = new CinnamonType(cid, type, Double.parseDouble(price));
            try {
                int editType = CinnamonTypeController.editType(cinnamonType);
                if (editType > 0) {

                    //refresh store list
                    setStoreList();

                    typeUTextField.setEditable(false);
                    priceUTextField.setEditable(false);

                    upDateButton.setEnabled(false);

                    cidUTextField.setText("");
                    typeUTextField.setText("");
                    priceUTextField.setText("");

                    JOptionPane.showMessageDialog(upDateButton, "Cinnamon Type Updated.");
                } else {
                    JOptionPane.showMessageDialog(upDateButton, "Try Again.");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(CinnamanTypeForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(upDateButton, "Enter the all Data.");
        }


    }//GEN-LAST:event_upDateButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        String cid = cidRTextField.getText();
        if (!"".equals(cid)) {
            try {
                int removeType = CinnamonTypeController.removeType(cid);
                if (removeType > 0) {

                    //refresh store list
                    setStoreList();

                    cidRTextField.setText("");
                    typeRTextField.setText("");
                    priceRTextField.setText("");

                    removeButton.requestFocus();
                    removeButton.setEnabled(false);

                    JOptionPane.showMessageDialog(removeButton, "removed");

                } else {
                    JOptionPane.showMessageDialog(removeButton, "try again");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(CinnamanTypeForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(removeButton, "Type IID");
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void cinnamonTypeListTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cinnamonTypeListTableMousePressed

//        int selectedRow = storeListTable.getSelectedRow();
//        if (storeListTable.isRowSelected(selectedRow)) {
//            String sid = (String) storeListTable.getValueAt(selectedRow, 0);
//            String name = (String) storeListTable.getValueAt(selectedRow, 1);
//            String date = (String) storeListTable.getValueAt(selectedRow, 3);
//
//            d_FTextField.setText(date);
//            sidUITextField.setText(sid);
//            nameUITextField.setText(name);
//
//            d_FTextField.setEditable(false);
//            d_TTextField.setEditable(false);
//            sidUITextField.setEditable(false);
//            nameUITextField.setEditable(false);
//
//        }
    }//GEN-LAST:event_cinnamonTypeListTableMousePressed

    private void addButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addButtonKeyPressed

//        String sid = sidNTextField.getText();
//        String name = nameNTextField.getText();
//        String qty = quntityNTextField.getText();
//
//        if (!"".equals(sid) & !"".equals(name) & !"".equals(qty)) {
//            Store store = new Store(sid, name, Double.parseDouble(qty), "");
//            try {
//                int addNew = StoreController.addNew(store);
//                if (addNew > 0) {
//
//                    //refresh store list
//                    setStoreList();
//
//                    nameNTextField.setEditable(false);
//                    quntityNTextField.setEditable(false);
//
//                    enterButton.setEnabled(false);
//
//                    sidNTextField.setText("");
//                    nameNTextField.setText("");
//                    quntityNTextField.setText("");
//
//                    JOptionPane.showMessageDialog(enterButton, "New Store Item entered.");
//                } else {
//                    JOptionPane.showMessageDialog(enterButton, "Try Again.");
//                }
//            } catch (ClassNotFoundException | SQLException ex) {
//                Logger.getLogger(CinnamanTypeForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        } else {
//            JOptionPane.showMessageDialog(enterButton, "Enter the all Data.");
//        }

    }//GEN-LAST:event_addButtonKeyPressed

    private void upDateButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_upDateButtonKeyPressed
//        String sid = sidUTextField.getText();
//        String qtyOH = quntityUTextField.getText();
//        String nStock = nStockUTextField.getText();
//
//        Store store;
//        if (!"".equals(sid) & !"".equals(qtyOH)) {
//            try {
//                if ("".equals(nStock)) {
//                    store = new Store(sid, null, Double.valueOf(qtyOH), "");
//
//                    int upDateQuntity = StoreController.upDateQuntity(store);
//                    if (upDateQuntity > 0) {
//                        //refresh store list
//                        setStoreList();
//
//                        nameUTextField.setEditable(false);
//                        quntityUTextField.setEditable(false);
//                        nStockUTextField.setEditable(false);
//
//                        upDateButton.setEnabled(false);
//
//                        sidUTextField.setText("");
//                        nameUTextField.setText("");
//                        quntityUTextField.setText("");
//                        nStockUTextField.setText("");
//                        JOptionPane.showMessageDialog(upDateButton, "Updated.");
//
//                    } else {
//                        JOptionPane.showMessageDialog(upDateButton, "Try Again.");
//                    }
//
//                } else {
//                    store = new Store(sid, null, (Double.valueOf(qtyOH) + Double.valueOf(nStock)), "");
//
//                    int upDateQuntity = StoreController.upDateQuntity(store);
//                    if (upDateQuntity > 0) {
//
//                        //refresh store list
//                        setStoreList();
//
//                        JOptionPane.showMessageDialog(rootPane, "Updated.");
//
//                        sidUTextField.setText("");
//                        nameUTextField.setText("");
//                        quntityUTextField.setText("");
//                        nStockUTextField.setText("");
//
//                    } else {
//                        JOptionPane.showMessageDialog(rootPane, "Try Again.");
//                    }
//                }
//            } catch (ClassNotFoundException | SQLException ex) {
//                Logger.getLogger(CinnamanTypeForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        } else {
//
//        }

        // TODO add your handling code here:
    }//GEN-LAST:event_upDateButtonKeyPressed

    private void removeButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_removeButtonKeyPressed
//        String sid = sidRTextField.getText();
//        if (!"".equals(sid)) {
//            try {
//                int removeBySid = StoreController.removeBySid(sid);
//                if (removeBySid > 0) {
//
//                    //refresh store list
//                    setStoreList();
//
//                    sidRTextField.setText("");
//                    nameRTextField.setText("");
//                    quntityRTextField.setText("");
//
//                    sidRTextField.requestFocus();
//                    removeButton.setEnabled(false);
//
//                    JOptionPane.showMessageDialog(removeButton, "removed");
//
//                } else {
//                    JOptionPane.showMessageDialog(removeButton, "try again");
//                }
//            } catch (ClassNotFoundException | SQLException ex) {
//                Logger.getLogger(CinnamanTypeForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        } else {
//
//            JOptionPane.showMessageDialog(removeButton, "Type IID");
//
//        }        // TODO add your handling code here:
    }//GEN-LAST:event_removeButtonKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane New;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField cidNTextField;
    private javax.swing.JTextField cidRTextField;
    private javax.swing.JTextField cidUTextField;
    private static javax.swing.JTable cinnamonTypeListTable;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField priceNTextField;
    private javax.swing.JTextField priceRTextField;
    private javax.swing.JTextField priceUTextField;
    private javax.swing.JButton removeButton;
    private javax.swing.JTextField typeNTextField;
    private javax.swing.JTextField typeRTextField;
    private javax.swing.JTextField typeUTextField;
    private javax.swing.JButton upDateButton;
    // End of variables declaration//GEN-END:variables
}
