/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author sajja
 */
public class DashBordForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminSetting
     */
    public DashBordForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CinnamanTypeButton = new javax.swing.JButton();
        changePasswordButton = new javax.swing.JButton();
        dashBordDesktopPane = new javax.swing.JDesktopPane();
        summaryButton = new javax.swing.JButton();
        supplierButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        CinnamanTypeButton.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        CinnamanTypeButton.setText("Cinnamon Type");
        CinnamanTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CinnamanTypeButtonActionPerformed(evt);
            }
        });

        changePasswordButton.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        changePasswordButton.setText("Change password");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashBordDesktopPaneLayout = new javax.swing.GroupLayout(dashBordDesktopPane);
        dashBordDesktopPane.setLayout(dashBordDesktopPaneLayout);
        dashBordDesktopPaneLayout.setHorizontalGroup(
            dashBordDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dashBordDesktopPaneLayout.setVerticalGroup(
            dashBordDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        summaryButton.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        summaryButton.setText("Summary");
        summaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryButtonActionPerformed(evt);
            }
        });

        supplierButton.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        supplierButton.setText("Suppliers");
        supplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashBordDesktopPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CinnamanTypeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(supplierButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(summaryButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changePasswordButton)
                        .addGap(0, 837, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CinnamanTypeButton)
                    .addComponent(changePasswordButton)
                    .addComponent(summaryButton)
                    .addComponent(supplierButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashBordDesktopPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CinnamanTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CinnamanTypeButtonActionPerformed
        dashBordDesktopPane.removeAll();
        repaint();
        CinnamanTypeForm cinnamanTypeForm = new CinnamanTypeForm();
        dashBordDesktopPane.add(cinnamanTypeForm);
        cinnamanTypeForm.setVisible(true);

    }//GEN-LAST:event_CinnamanTypeButtonActionPerformed

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        dashBordDesktopPane.removeAll();
        repaint();
        AdminChangePasswordForm acpf = new AdminChangePasswordForm();
        dashBordDesktopPane.add(acpf);
        acpf.setVisible(true);

    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void summaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryButtonActionPerformed
//        DesktopPane1.removeAll();
//        repaint();
//        AdminEmployeeForm aef = new AdminEmployeeForm();
//        DesktopPane1.add(aef);
//        aef.setVisible(true);

    }//GEN-LAST:event_summaryButtonActionPerformed

    private void supplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierButtonActionPerformed
        dashBordDesktopPane.removeAll();
        repaint();
        SupplierForm supplierForm = new SupplierForm();
        dashBordDesktopPane.add(supplierForm);
        supplierForm.setVisible(true);
    }//GEN-LAST:event_supplierButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBordForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CinnamanTypeButton;
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JDesktopPane dashBordDesktopPane;
    private javax.swing.JButton summaryButton;
    private javax.swing.JButton supplierButton;
    // End of variables declaration//GEN-END:variables
}
