/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ChequeController;
import controller.CinnamonTypeController;
import controller.PaymentController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cheque;
import model.CinnamonType;
import model.Payment;
import validation.AutoId;
import validation.ComboSearch;

/**
 *
 * @author Sachitha
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    DefaultTableModel dtmOrderTable;

    public MainForm() {
        initComponents();
        dtmOrderTable = (DefaultTableModel) orderTable.getModel();

        showOrdersInTable();
        setCinnamonTypeComboBox();
        new ComboSearch().setSearchableComboBox(cinnamonTypeComboBox, "No Catagory");

        //payment next Id
        try {
            String pid = AutoId.getNextId("tab_payment", "pid", "");
            paymentNoTextField.setText(pid);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void showOrdersInTable() {
        dtmOrderTable.setRowCount(0);
        try {
            ArrayList<Payment> allTempOrders = PaymentController.getAllTempOrders();

            for (Payment Order : allTempOrders) {
                String[] ar = {Order.getCid(),
                    String.valueOf(Order.getGrossWeight()),
                    String.valueOf(Order.getWetWeight()),
                    String.valueOf(Order.getReduceWeight()),
                    String.valueOf(Order.getAmount())};

                dtmOrderTable.addRow(ar);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setCinnamonTypeComboBox() {
        cinnamonTypeComboBox.removeAllItems();

        try {
            ArrayList<String> types = CinnamonTypeController.getAllTypes();
            for (String type : types) {

                String arCatagry[] = {type};
                cinnamonTypeComboBox.addItem(arCatagry[0]);

                cinnamonTypeComboBox.setSelectedItem(null);

            }
        } catch (ClassNotFoundException | SQLException e) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, e);
        }

    }

////    /**
////     * This method is called from within the constructor to initialize the form.
////     * WARNING: Do NOT modify this code. The content of this method is always
////     * regenerated by the Form Editor.
////     */
////    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        grosssWTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        paymentNoTextField = new javax.swing.JTextField();
        reduceWTextField = new javax.swing.JTextField();
        cinnamonTypeComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        wetWTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cidComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        chequeCheckBox = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        chequeNoTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        nicTextField = new javax.swing.JTextField();
        bankNameTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        newSupplierButton = new javax.swing.JButton();
        payButton = new javax.swing.JButton();
        totalTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dashBordButton = new javax.swing.JButton();
        mainDesktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addButton.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        addButton.setText("ADD");
        addButton.setEnabled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        addButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addButtonKeyPressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel21.setText("Reduce Weight");

        orderTable.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cynnamon Type", "Gross Weight", "Wet Weight", "Reduce Weight", "Amount"
            }
        ));
        jScrollPane2.setViewportView(orderTable);

        grosssWTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grosssWTextFieldActionPerformed(evt);
            }
        });
        grosssWTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                grosssWTextFieldKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel5.setText("Payment No:");

        paymentNoTextField.setEnabled(false);
        paymentNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentNoTextFieldActionPerformed(evt);
            }
        });
        paymentNoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paymentNoTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paymentNoTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paymentNoTextFieldKeyTyped(evt);
            }
        });

        reduceWTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reduceWTextFieldActionPerformed(evt);
            }
        });
        reduceWTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reduceWTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reduceWTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                reduceWTextFieldKeyTyped(evt);
            }
        });

        cinnamonTypeComboBox.setEditable(true);
        cinnamonTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinnamonTypeComboBoxActionPerformed(evt);
            }
        });
        cinnamonTypeComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cinnamonTypeComboBoxKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel6.setText("Cynnamon Type");

        wetWTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wetWTextFieldActionPerformed(evt);
            }
        });
        wetWTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                wetWTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wetWTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wetWTextFieldKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel15.setText("Gross Weight");

        jLabel23.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel23.setText("Wet Weight");

        cidComboBox.setEditable(true);
        cidComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidComboBoxActionPerformed(evt);
            }
        });
        cidComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cidComboBoxKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel9.setText("Cinnamon ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paymentNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cidComboBox, 0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cinnamonTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(grosssWTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(wetWTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reduceWTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(paymentNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel15)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wetWTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grosssWTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cinnamonTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reduceWTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cidComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel7.setText("Payment");

        chequeCheckBox.setText("Cheque");
        chequeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequeCheckBoxActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel16.setText("Cheque No");

        chequeNoTextField.setEnabled(false);
        chequeNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequeNoTextFieldActionPerformed(evt);
            }
        });
        chequeNoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chequeNoTextFieldKeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel17.setText("NIC");

        nicTextField.setEnabled(false);
        nicTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicTextFieldActionPerformed(evt);
            }
        });
        nicTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nicTextFieldKeyPressed(evt);
            }
        });

        bankNameTextField.setEnabled(false);
        bankNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankNameTextFieldActionPerformed(evt);
            }
        });
        bankNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bankNameTextFieldKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel18.setText("Bank Name");

        newSupplierButton.setText("New Supplier");
        newSupplierButton.setEnabled(false);
        newSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSupplierButtonActionPerformed(evt);
            }
        });

        payButton.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        payButton.setText("Pay/Print");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        totalTextField.setEditable(false);
        totalTextField.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        totalTextField.setForeground(new java.awt.Color(255, 0, 0));
        totalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel8.setText("Total :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chequeNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newSupplierButton)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chequeCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 463, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(243, Short.MAX_VALUE)
                    .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chequeCheckBox)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(chequeNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(nicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(2, 2, 2)
                .addComponent(newSupplierButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(bankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(127, 127, 127)
                    .addComponent(payButton)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("CSK Exports");

        dashBordButton.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        dashBordButton.setText("Dash Bord");
        dashBordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashBordButtonActionPerformed(evt);
            }
        });
        dashBordButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dashBordButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashBordButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashBordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainDesktopPaneLayout = new javax.swing.GroupLayout(mainDesktopPane);
        mainDesktopPane.setLayout(mainDesktopPaneLayout);
        mainDesktopPaneLayout.setHorizontalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        mainDesktopPaneLayout.setVerticalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mainDesktopPane))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(mainDesktopPane))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String cid = (String) cidComboBox.getSelectedItem();
        String grossWeightStr = grosssWTextField.getText();
        String wetWeightStr = wetWTextField.getText();
        String reduceWeightStr = reduceWTextField.getText();
        String cinnamanType = (String) cinnamonTypeComboBox.getSelectedItem();
        if (!cid.equals("") && !grossWeightStr.equals("") && !cinnamanType.equals("")) {

            double grossWeight = Double.valueOf(grossWeightStr);
            double wetWeight = 0;
            double reduceWeight = 0;
            CinnamonType allFromCID = null;
            if (!wetWeightStr.equals("")) {
                wetWeight = Double.parseDouble(wetWeightStr);
            }
            if (!reduceWeightStr.equals("")) {
                reduceWeight = Double.parseDouble(reduceWeightStr);
            }
            //get price per 1kg
            try {

                allFromCID = CinnamonTypeController.getAllFromCID(cid);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (allFromCID != null && allFromCID.getPrice() > 0) {
                //calcuate amount
                double amount = (grossWeight - (wetWeight + reduceWeight)) * allFromCID.getPrice();

                Payment payment = new Payment();
                payment.setCid(cid);
                payment.setGrossWeight(grossWeight);
                payment.setReduceWeight(reduceWeight);
                payment.setWetWeight(wetWeight);
                payment.setAmount(amount);

                int addPaymentToTemp = 0;

                try {
                    addPaymentToTemp = PaymentController.addPaymentToTemp(payment);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (addPaymentToTemp > 0) {

                    String ar[] = {cinnamanType, String.valueOf(payment.getGrossWeight()), String.valueOf(payment.getWetWeight()), String.valueOf(payment.getReduceWeight()), String.valueOf(payment.getAmount())};
                    dtmOrderTable.addRow(ar);

                    cidComboBox.removeAllItems();
                    cinnamonTypeComboBox.removeAllItems();
                    grosssWTextField.setText("");
                    wetWTextField.setText("");
                    reduceWTextField.setText("");
                    addButton.setEnabled(false);

                } else {
                    JOptionPane.showMessageDialog(orderTable, "Try again");
                }

            } else {
                JOptionPane.showMessageDialog(orderTable, "Cinnamon Id is not valid");
            }

        } else {
            JOptionPane.showMessageDialog(orderTable, "Enter All Details");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void addButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonKeyPressed

    private void grosssWTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grosssWTextFieldActionPerformed
        wetWTextField.requestFocus();
    }//GEN-LAST:event_grosssWTextFieldActionPerformed

    private void grosssWTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grosssWTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_grosssWTextFieldKeyPressed

    private void paymentNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentNoTextFieldActionPerformed

    private void paymentNoTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentNoTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentNoTextFieldKeyPressed

    private void paymentNoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentNoTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentNoTextFieldKeyReleased

    private void paymentNoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentNoTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentNoTextFieldKeyTyped

    private void reduceWTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reduceWTextFieldActionPerformed
        addButton.setEnabled(true);
        addButton.requestFocus();
    }//GEN-LAST:event_reduceWTextFieldActionPerformed

    private void reduceWTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reduceWTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_reduceWTextFieldKeyPressed

    private void reduceWTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reduceWTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_reduceWTextFieldKeyReleased

    private void reduceWTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reduceWTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_reduceWTextFieldKeyTyped

    private void cinnamonTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinnamonTypeComboBoxActionPerformed
        grosssWTextField.requestFocus();
    }//GEN-LAST:event_cinnamonTypeComboBoxActionPerformed

    private void cinnamonTypeComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cinnamonTypeComboBoxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinnamonTypeComboBoxKeyPressed

    private void wetWTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wetWTextFieldActionPerformed
        reduceWTextField.requestFocus();
    }//GEN-LAST:event_wetWTextFieldActionPerformed

    private void wetWTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wetWTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_wetWTextFieldKeyPressed

    private void wetWTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wetWTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_wetWTextFieldKeyReleased

    private void wetWTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wetWTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_wetWTextFieldKeyTyped

    private void chequeNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequeNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chequeNoTextFieldActionPerformed

    private void chequeNoTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chequeNoTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chequeNoTextFieldKeyPressed

    private void nicTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicTextFieldActionPerformed

    private void nicTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicTextFieldKeyPressed

    private void bankNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankNameTextFieldActionPerformed

    private void bankNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bankNameTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankNameTextFieldKeyPressed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed

        int pid = Integer.parseInt(paymentNoTextField.getText());
        System.out.println("pid  " + pid);
        if (pid > 0) {
            try {
                //get orders from temp table
                ArrayList<Payment> allTempOrders = PaymentController.getAllTempOrders();
                for (Payment allTempOrder : allTempOrders) {
                    allTempOrder.setPid(pid);
                    //add it to payment table
                    int addPayment = PaymentController.addPayment(allTempOrder);
                    if (chequeCheckBox.isSelected() && addPayment > 0) {
                        String chequeNo = chequeNoTextField.getText();
                        String nic = nicTextField.getText();
                        String bankName = bankNameTextField.getText();
                        if (!chequeNo.equals("") && !nic.equals("") && !bankName.equals("")) {
                            Cheque cheque = new Cheque();
                            cheque.setCheqNo(chequeNo);
                            cheque.setPid(pid);
                            cheque.setNic(nic);
                            cheque.setBankName(bankName);
                            int addCheque = ChequeController.addCheque(cheque);
                            if (addCheque > 0) {
                                JOptionPane.showMessageDialog(orderTable, "Paid and check is issued");

                            } else {
                            }
                        } else {
                        }

                    } else if (addPayment > 0 && !chequeCheckBox.isSelected()) {
                        JOptionPane.showMessageDialog(cidComboBox, "paid");
                    }

                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
        }


    }//GEN-LAST:event_payButtonActionPerformed

    private void totalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTextFieldActionPerformed

    private void dashBordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashBordButtonActionPerformed

        DashBordPasswordForm dashBordPasswordForm = new DashBordPasswordForm(this, rootPaneCheckingEnabled);
        dashBordPasswordForm.setVisible(true);


    }//GEN-LAST:event_dashBordButtonActionPerformed

    private void dashBordButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dashBordButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashBordButtonKeyPressed

    private void newSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSupplierButtonActionPerformed
        mainDesktopPane.removeAll();
        repaint();
        SupplierForm supplierForm = new SupplierForm();
        mainDesktopPane.add(supplierForm);
        supplierForm.setVisible(true);
    }//GEN-LAST:event_newSupplierButtonActionPerformed

    private void cidComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidComboBoxActionPerformed
        String cid = (String) cidComboBox.getSelectedItem();
        if (cid != null) {
            try {
                CinnamonType cinnamonFromCID = CinnamonTypeController.getTypeFromCID(cid);
                if (cinnamonFromCID != null) {
                    cinnamonTypeComboBox.setSelectedItem(cinnamonFromCID.getType());
                    grosssWTextField.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(cidComboBox, "Invalid Cinnamaon ID");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(cinnamonTypeComboBox, "TEnter Cinnamon ID.");
        }
    }//GEN-LAST:event_cidComboBoxActionPerformed

    private void cidComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cidComboBoxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidComboBoxKeyPressed

    private void chequeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequeCheckBoxActionPerformed
        if (chequeCheckBox.isSelected()) {
            chequeNoTextField.setEnabled(true);
            nicTextField.setEnabled(true);
            newSupplierButton.setEnabled(true);
            bankNameTextField.setEnabled(true);

        } else {
            chequeNoTextField.setEnabled(false);
            nicTextField.setEnabled(false);
            newSupplierButton.setEnabled(false);
            bankNameTextField.setEnabled(false);
        }
        chequeNoTextField.setText("");
        nicTextField.setText("");
        bankNameTextField.setText("");

    }//GEN-LAST:event_chequeCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField bankNameTextField;
    private javax.swing.JCheckBox chequeCheckBox;
    private javax.swing.JTextField chequeNoTextField;
    private javax.swing.JComboBox cidComboBox;
    private javax.swing.JComboBox cinnamonTypeComboBox;
    private javax.swing.JButton dashBordButton;
    private javax.swing.JTextField grosssWTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDesktopPane mainDesktopPane;
    private javax.swing.JButton newSupplierButton;
    private javax.swing.JTextField nicTextField;
    private javax.swing.JTable orderTable;
    private javax.swing.JButton payButton;
    private javax.swing.JTextField paymentNoTextField;
    private javax.swing.JTextField reduceWTextField;
    private static javax.swing.JTextField totalTextField;
    private javax.swing.JTextField wetWTextField;
    // End of variables declaration//GEN-END:variables
}
