/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sajja
 */
public class SupplierForm extends javax.swing.JInternalFrame {

//    private String passDate;
//    DefaultTableModel dtmEL;
//    DefaultTableModel dtmWD;
//    DefaultTableModel dtmWT;
//    DefaultTableModel dtmAL;

    /**
     * Creates new form AdminEmployeeForm
     */
    public SupplierForm() {
        initComponents();
//        passDate = MainForm.passDate();
//
//        dateTextField.setText(passDate);
//        f_TextField.setText(passDate);
//        t_TextField.setText(passDate);
//        dateSalaryTextField.setText(passDate);
//
//        dtmEL = (DefaultTableModel) employeeListTable.getModel();
//        dtmWD = (DefaultTableModel) wrkdTable.getModel();
//        dtmWT = (DefaultTableModel) wrkTTable.getModel();
//        dtmAL = (DefaultTableModel) salaryTable.getModel();
//
//        try {
//            ArrayList<Employee> allEmployee = EmployeeController.getAllEmployee();
//            for (Employee employee : allEmployee) {
//                String ar[] = {employee.getEid(), employee.getName(), employee.getAddress(), String.valueOf(employee.getTpNo())};
//                dtmEL.addRow(ar);
//
//            }
//
//        } catch (ClassNotFoundException | SQLException ex) {
//            Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addressNTextField = new javax.swing.JTextField();
        tpNoNTextField = new javax.swing.JTextField();
        nameNTextField = new javax.swing.JTextField();
        eidNTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        removeButton = new javax.swing.JButton();
        nameRTextField = new javax.swing.JTextField();
        eidRTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        addressRTextField = new javax.swing.JTextField();
        tpNoRTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        nameUTextField = new javax.swing.JTextField();
        eidUTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addressUTextField = new javax.swing.JTextField();
        tpNoUTextField = new javax.swing.JTextField();
        upDateButton = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeListTable = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTabbedPane1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel5.setText("Address :");

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel6.setText("Mobile No :");

        addressNTextField.setEditable(false);
        addressNTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressNTextFieldActionPerformed(evt);
            }
        });

        tpNoNTextField.setEditable(false);
        tpNoNTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpNoNTextFieldActionPerformed(evt);
            }
        });
        tpNoNTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpNoNTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tpNoNTextFieldKeyTyped(evt);
            }
        });

        nameNTextField.setEditable(false);
        nameNTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameNTextFieldActionPerformed(evt);
            }
        });

        eidNTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidNTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel7.setText("Supplier NIC :");

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel8.setText("Name :");

        enterButton.setBackground(new java.awt.Color(51, 102, 255));
        enterButton.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        enterButton.setText("Enter");
        enterButton.setEnabled(false);
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        enterButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eidNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressNTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameNTextField)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(tpNoNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 204, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(enterButton)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(eidNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nameNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addressNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tpNoNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("New Supplier", jPanel4);

        removeButton.setBackground(new java.awt.Color(51, 102, 255));
        removeButton.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        removeButton.setText("Remove");
        removeButton.setEnabled(false);
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        removeButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                removeButtonKeyPressed(evt);
            }
        });

        nameRTextField.setEditable(false);

        eidRTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidRTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel9.setText("Supplier NIC :");

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel10.setText("Name :");

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel11.setText("Address :");

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel12.setText("Mobile No :");

        addressRTextField.setEditable(false);

        tpNoRTextField.setEditable(false);
        tpNoRTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpNoRTextFieldActionPerformed(evt);
            }
        });
        tpNoRTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpNoRTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eidRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(54, 54, 54)
                                .addComponent(nameRTextField)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tpNoRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 214, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(addressRTextField)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(eidRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nameRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(addressRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tpNoRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Remove Supplier", jPanel3);

        nameUTextField.setEditable(false);
        nameUTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameUTextFieldActionPerformed(evt);
            }
        });

        eidUTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidUTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel1.setText("Supplier NIC :");

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel3.setText("Address :");

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel4.setText("Mobile No :");

        addressUTextField.setEditable(false);
        addressUTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressUTextFieldActionPerformed(evt);
            }
        });

        tpNoUTextField.setEditable(false);
        tpNoUTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpNoUTextFieldActionPerformed(evt);
            }
        });
        tpNoUTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpNoUTextFieldKeyReleased(evt);
            }
        });

        upDateButton.setBackground(new java.awt.Color(51, 102, 255));
        upDateButton.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        upDateButton.setText("Update");
        upDateButton.setEnabled(false);
        upDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upDateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eidUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(54, 54, 54)
                        .addComponent(nameUTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tpNoUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 204, Short.MAX_VALUE))
                            .addComponent(addressUTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(upDateButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eidUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addressUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tpNoUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upDateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update Supplier", jPanel1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jLabel32.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel32.setText("Employee's Details");

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 102, 255));
        jLabel14.setText("Supplier Details");

        employeeListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIC", "Name", "address", "Mobile No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(employeeListTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eidUTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidUTextFieldActionPerformed
//        String eid = eidUTextField.getText();
//        try {
//            Employee employee = EmployeeController.searchEmplyeeUsingEid(eid);
//            if (employee != null) {
//                nameUTextField.setText(employee.getName());
//                addressUTextField.setText(employee.getAddress());
//                tpNoUTextField.setText(String.valueOf(employee.getTpNo()));
//
//                nameUTextField.setEditable(true);
//                addressUTextField.setEditable(true);
//                tpNoUTextField.setEditable(true);
//
//                upDateButton.setEnabled(true);
//
//                nameUTextField.requestFocus();
//            } else {
//
//                nameUTextField.setText("");
//                addressUTextField.setText("");
//                tpNoUTextField.setText("");
//                JOptionPane.showMessageDialog(eidUTextField, "this Employee Id is not available");
//            }
//
//        } catch (ClassNotFoundException | SQLException ex) {
//            Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_eidUTextFieldActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
//        String eid = eidNTextField.getText();
//        String name = nameNTextField.getText();
//        String address = addressNTextField.getText();
//        String tpNo = tpNoNTextField.getText();
//
//        if (!"".equals(eid) & !"".equals(name) & !"".equals(address) & !"".equals(tpNo)) {
//            Employee employee = new Employee(eid, name, address, tpNo);
//            try {
//                int addEmployee = EmployeeController.addEmployee(employee);
//                if (addEmployee > 0) {
//
//                    //add to the employeelit table
//                    dtmEL.setRowCount(0);
//                    ArrayList<Employee> allEmployee = EmployeeController.getAllEmployee();
//                    for (Employee employee1 : allEmployee) {
//                        String ar[] = {employee1.getEid(), employee1.getName(), employee1.getAddress(), String.valueOf(employee1.getTpNo())};
//                        dtmEL.addRow(ar);
//                    }
//                    nameNTextField.setEditable(false);
//                    addressNTextField.setEditable(false);
//                    tpNoNTextField.setEditable(false);
//
//                    enterButton.setEnabled(false);
//
//                    eidNTextField.setText("");
//                    nameNTextField.setText("");
//                    addressNTextField.setText("");
//                    tpNoNTextField.setText("");
//
//                    JOptionPane.showMessageDialog(enterButton, "New Employee entered..");
//                }
//
//            } catch (ClassNotFoundException | SQLException ex) {
//                Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//        } else {
//            JOptionPane.showMessageDialog(enterButton, "Type all details");
//        }
    }//GEN-LAST:event_enterButtonActionPerformed

    private void upDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upDateButtonActionPerformed
//        String eid = eidUTextField.getText();
//        String name = nameUTextField.getText();
//        String address = addressUTextField.getText();
//        String tpNo = tpNoUTextField.getText();
//
//        if (!"".equals(eid) & !"".equals(name) & !"".equals(address) & !"".equals(tpNo)) {
//
//            Employee employee = new Employee(eid, name, address, tpNo);
//
//            try {
//                int upDateEmployee = EmployeeController.upDateEmployee(employee);
//                if (upDateEmployee > 0) {
//
//                    //add to the employeelit table
//                    dtmEL.setRowCount(0);
//                    ArrayList<Employee> allEmployee = EmployeeController.getAllEmployee();
//                    for (Employee employee1 : allEmployee) {
//                        String ar[] = {employee1.getEid(), employee1.getName(), employee1.getAddress(), String.valueOf(employee1.getTpNo())};
//                        dtmEL.addRow(ar);
//
//                    }
//
//                    nameUTextField.setEditable(false);
//                    addressUTextField.setEditable(false);
//                    tpNoUTextField.setEditable(false);
//
//                    upDateButton.setEnabled(false);
//
//                    eidUTextField.setText("");
//                    nameUTextField.setText("");
//                    addressUTextField.setText("");
//                    tpNoUTextField.setText("");
//
//                    eidUTextField.requestFocus();
//
//                    JOptionPane.showMessageDialog(upDateButton, "Updated..");
//
//                }
//            } catch (ClassNotFoundException | SQLException ex) {
//                Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }


    }//GEN-LAST:event_upDateButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed

//        String eid = eidRTextField.getText();
//        if (!"".equals(eid)) {
//            try {
//                int removeEmployee = EmployeeController.removeEmployee(eid);
//                if (removeEmployee > 0) {
//
//                    eidRTextField.setText("");
//                    nameRTextField.setText("");
//                    addressRTextField.setText("");
//                    tpNoRTextField.setText("");
//
//                    //add to the employeelit table
//                    dtmEL.setRowCount(0);
//                    ArrayList<Employee> allEmployee = EmployeeController.getAllEmployee();
//                    for (Employee employee1 : allEmployee) {
//                        String ar[] = {employee1.getEid(), employee1.getName(), employee1.getAddress(), String.valueOf(employee1.getTpNo())};
//                        dtmEL.addRow(ar);
//
//                    }
//                    JOptionPane.showMessageDialog(removeButton, "employee removed");
//                }
//            } catch (ClassNotFoundException | SQLException ex) {
//                Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        } else {
//
//            JOptionPane.showMessageDialog(rootPane, "enter the emplyee ID");
//        }


    }//GEN-LAST:event_removeButtonActionPerformed

    private void eidRTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidRTextFieldActionPerformed
//        String eid = eidRTextField.getText();
//        if (!"".equals(eid)) {
//            try {
//                Employee employee = EmployeeController.searchEmplyeeUsingEid(eid);
//                if (employee != null) {
//                    nameRTextField.setText(employee.getName());
//                    addressRTextField.setText(employee.getAddress());
//                    tpNoRTextField.setText(String.valueOf(employee.getTpNo()));
//
//                    removeButton.setEnabled(true);
//                    removeButton.requestFocus();
//                } else {
//
//                    nameUTextField.setText("");
//                    addressRTextField.setText("");
//                    tpNoRTextField.setText("");
//                    JOptionPane.showMessageDialog(eidRTextField, "this Employee Id is not available");
//                }
//
//            } catch (ClassNotFoundException | SQLException ex) {
//                Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        } else {
//            JOptionPane.showMessageDialog(eidRTextField, "Type EID.");
//        }

    }//GEN-LAST:event_eidRTextFieldActionPerformed

    private void eidNTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidNTextFieldActionPerformed
//        String eid = eidNTextField.getText();
//        if (!"".equals(eid)) {
//
//            try {
//                String checkEmplyeeUsingEid = EmployeeController.checkEmplyeeUsingEid(eid);
//                if (checkEmplyeeUsingEid == null) {
//                    nameNTextField.setEditable(true);
//                    nameNTextField.requestFocus();
//
//                } else {
//                    JOptionPane.showMessageDialog(eidNTextField, "This EID already entered.");
//                }
//            } catch (ClassNotFoundException | SQLException ex) {
//                Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//        } else {
//            JOptionPane.showMessageDialog(eidNTextField, "Type Eid.");
//        }


    }//GEN-LAST:event_eidNTextFieldActionPerformed

    private void tpNoNTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpNoNTextFieldActionPerformed
//        String text = tpNoNTextField.getText();
//        if (!"".equals(text)) {
//
//            enterButton.setEnabled(true);
//            enterButton.requestFocus();
//
//        } else {
//            JOptionPane.showMessageDialog(tpNoNTextField, "Type Mobile No.");
//        }


    }//GEN-LAST:event_tpNoNTextFieldActionPerformed

    private void tpNoNTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpNoNTextFieldKeyTyped

    }//GEN-LAST:event_tpNoNTextFieldKeyTyped

    private void tpNoNTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpNoNTextFieldKeyReleased
//        CheckNumber.checktelephone(tpNoNTextField);


    }//GEN-LAST:event_tpNoNTextFieldKeyReleased

    private void tpNoRTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpNoRTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpNoRTextFieldActionPerformed

    private void tpNoRTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpNoRTextFieldKeyReleased
//        CheckNumber.checktelephone(tpNoRTextField);
    }//GEN-LAST:event_tpNoRTextFieldKeyReleased

    private void tpNoUTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpNoUTextFieldActionPerformed
//        upDateButton.requestFocus();
    }//GEN-LAST:event_tpNoUTextFieldActionPerformed

    private void tpNoUTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpNoUTextFieldKeyReleased
//        CheckNumber.checktelephone(tpNoUTextField);
    }//GEN-LAST:event_tpNoUTextFieldKeyReleased

    private void nameNTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameNTextFieldActionPerformed
//        String text = nameNTextField.getText();
//        if (!"".equals(text)) {
//
//            addressNTextField.setEditable(true);
//            addressNTextField.requestFocus();
//
//        } else {
//            JOptionPane.showMessageDialog(nameNTextField, "Type name");
//        }

    }//GEN-LAST:event_nameNTextFieldActionPerformed

    private void addressNTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressNTextFieldActionPerformed
//        String text = addressNTextField.getText();
//        if (!"".equals(text)) {
//
//            tpNoNTextField.setEditable(true);
//            tpNoNTextField.requestFocus();
//
//        } else {
//            JOptionPane.showMessageDialog(addressNTextField, "Type address");
//        }

    }//GEN-LAST:event_addressNTextFieldActionPerformed

    private void nameUTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameUTextFieldActionPerformed
//        addressUTextField.requestFocus();
    }//GEN-LAST:event_nameUTextFieldActionPerformed

    private void addressUTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressUTextFieldActionPerformed
//        tpNoUTextField.requestFocus();
    }//GEN-LAST:event_addressUTextFieldActionPerformed

    private void enterButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterButtonKeyPressed
//        String eid = eidNTextField.getText();
//        String name = nameNTextField.getText();
//        String address = addressNTextField.getText();
//        String tpNo = tpNoNTextField.getText();
//
//        if (!"".equals(eid) & !"".equals(name) & !"".equals(address) & !"".equals(tpNo)) {
//            Employee employee = new Employee(eid, name, address, tpNo);
//            try {
//                int addEmployee = EmployeeController.addEmployee(employee);
//                if (addEmployee > 0) {
//
//                    //add to the employeelit table
//                    dtmEL.setRowCount(0);
//                    ArrayList<Employee> allEmployee = EmployeeController.getAllEmployee();
//                    for (Employee employee1 : allEmployee) {
//                        String ar[] = {employee1.getEid(), employee1.getName(), employee1.getAddress(), String.valueOf(employee1.getTpNo())};
//                        dtmEL.addRow(ar);
//
//                        nameNTextField.setEditable(false);
//                        addressNTextField.setEditable(false);
//                        tpNoNTextField.setEditable(false);
//
//                        enterButton.setEnabled(false);
//
//                        eidNTextField.setText("");
//                        nameNTextField.setText("");
//                        addressNTextField.setText("");
//                        tpNoNTextField.setText("");
//
//                    }
//                    JOptionPane.showMessageDialog(enterButton, "New Employee entered..");
//                }
//
//            } catch (ClassNotFoundException | SQLException ex) {
//                Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//        } else {
//            JOptionPane.showMessageDialog(enterButton, "Type all details");
//        }
    }//GEN-LAST:event_enterButtonKeyPressed

    private void removeButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_removeButtonKeyPressed
//        String eid = eidRTextField.getText();
//        if (!"".equals(eid)) {
//            try {
//                int removeEmployee = EmployeeController.removeEmployee(eid);
//                if (removeEmployee > 0) {
//
//                    eidRTextField.setText("");
//                    nameRTextField.setText("");
//                    addressRTextField.setText("");
//                    tpNoRTextField.setText("");
//
//                    //add to the employeelit table
//                    dtmEL.setRowCount(0);
//                    ArrayList<Employee> allEmployee = EmployeeController.getAllEmployee();
//                    for (Employee employee1 : allEmployee) {
//                        String ar[] = {employee1.getEid(), employee1.getName(), employee1.getAddress(), String.valueOf(employee1.getTpNo())};
//                        dtmEL.addRow(ar);
//
//                    }
//                    JOptionPane.showMessageDialog(removeButton, "employee removed");
//                }
//            } catch (ClassNotFoundException | SQLException ex) {
//                Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        } else {
//
//            JOptionPane.showMessageDialog(rootPane, "enter the emplyee ID");
//        }


    }//GEN-LAST:event_removeButtonKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressNTextField;
    private javax.swing.JTextField addressRTextField;
    private javax.swing.JTextField addressUTextField;
    private javax.swing.JTextField eidNTextField;
    private javax.swing.JTextField eidRTextField;
    private javax.swing.JTextField eidUTextField;
    private javax.swing.JTable employeeListTable;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameNTextField;
    private javax.swing.JTextField nameRTextField;
    private javax.swing.JTextField nameUTextField;
    private javax.swing.JButton removeButton;
    private javax.swing.JTextField tpNoNTextField;
    private javax.swing.JTextField tpNoRTextField;
    private javax.swing.JTextField tpNoUTextField;
    private javax.swing.JButton upDateButton;
    // End of variables declaration//GEN-END:variables
}
